name: titanic_ps
channels:
  - defaults
  - conda-forge
dependencies:
  - seaborn
  - matplotlib==3.7.1
  - numpy==1.22.3
  - pandas==1.4.2
  - jupyter==1.0.0
  - scikit-learn
  - wordcloud
  - pathlib